local colors = {
  dark0 = "#2d3443",
  dark1 = "#373e4d",
  bright_black = "#4c566a",
  bright_blue = "#7acbea",
  bright_cyan = "#a1d5f7",
  bright_green = "#44eb9f",
  bright_magenta = "#d8a6f4",
  bright_red = "#fa74b2",
  bright_white = "#f9f9f9",
  bright_yellow = "#faa687",
  light_pink = "#ffd7d7",
  black = "#434c5e",
  blue = "#63c5ea",
  cyan = "#89ccf7",
  green = "#2be491",
  magenta = "#cf8ef4",
  red = "#fa5aa4",
  white = "#efefef",
  yellow = "#fa946e",
}

local groups = {
    Normal = { fg = colors.bright_white, bg = nil },
    Special = { fg = colors.bright_red, bold = true },
    Comment = { fg = colors.bright_black },
    LineNr = { fg = colors.bright_black },
    Constant = { fg = colors.cyan },
    String = { fg = colors.bright_yellow, italic = true },
    Character = { fg = colors.bright_yellow, bold = true },
    SpecialChar = { fg = colors.red, bold = true},
    Boolean = { fg = colors.cyan },
    Identifier = { fg = colors.magenta },
    Function = { fg = colors.magenta, bold = true },
    Statement = { fg = colors.red },
    Operator = { fg = colors.bright_magenta, bold = true },
    Keyword = { fg = colors.bright_magenta},
    Exception = { fg = colors.red },
    PreProc = { fg = colors.bright_cyan },
    Include = { fg = colors.bright_cyan, italic = true },
    Define = { fg = colors.bright_cyan, italic = true },
    Macro = { fg = colors.bright_cyan, italic = true },
    Type = { fg = colors.green, bold = true },
    Typedef = { link = "Type" },
    Structure = { fg = colors.yellow, bold = true },
    Error = { fg = colors.black, bg = colors.bright_red },
    Todo = { fg = colors.green, bg = colors.bright_blue },
    VarId = { fg = colors.magenta },
    ConId = { link = "Type" },
    hsVarSym = { fg = colors.bright_cyan, bold = true },
    hsConSym = { fg = colors.red, bold = true },
    hsNumber = { fg = colors.blue },
    NormalFloat = { bg = colors.dark0},
    FloatBorder = { fg = colors.bright_black },
    Directory = { fg = colors.bright_blue, bold = true },
    CursorLine = { fg = colors.red, italic = true },
    Pmenu = { fg = colors.dark1, bg = colors.magenta },
    PmenuSel = { fg = colors.bright_magenta, bg = colors.dark0 },
    DiagnosticError = { fg = colors.red },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
    DiagnosticWarn = { fg = colors.yellow },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticInfo = { fg = colors.bright_cyan },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.bright_blue },
    DiagnosticHint = { fg = colors.bright_white },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.white },
    Search = { fg = colors.black, bg = colors.bright_red },
    IncSearch = { link = "Search" },
    CurSearch = { link = "Search" },
    StatusLineEnd = { fg = colors.dark1, bg = colors.dark1 },
    NormalModeColor = { fg = colors.dark1, bg = colors.bright_cyan, bold = true },
    NormalModeSep = { fg = colors.bright_cyan, bg = colors.light_pink },
    FilenameColor = { fg = colors.dark1, bg = colors.light_pink },
    FilenameSepColor = { fg = colors.light_pink, bg = colors.dark1 },
    VisualModeColor = { fg = colors.dark1, bg = colors.bright_white, bold = true },
    VisualModeSep = { fg = colors.bright_white, bg = colors.light_pink },
    VisualLineModeColor = { link = "VisualModeColor" },
    VisualLineModeSep = { link = "VisualModeSep" },
    VisualBlockModeColor = { link = "VisualModeColor" },
    VisualBlockModeSep = { link = "VisualModeSep" },
    SelectModeColor = { link = "VisualModeColor" },
    SelectModeSep = { link = "VisualModeSep" },
    SelectLineModeColor = { link = "VisualModeColor" },
    SelectLineModeSep = { link = "VisualModeSep" },
    SelectBlockModeColor = { link = "VisualModeColor" },
    SelectBlockModeSep = { link = "VisualModeSep" },
    InsertModeColor = { fg = colors.dark1, bg = colors.green, bold = true },
    InsertModeSep = { fg = colors.green, bg = colors.light_pink },
    ReplaceModeColor = { fg = colors.dark1, bg = colors.red, bold = true },
    ReplaceModeSep = { fg = colors.red, bg = colors.light_pink },
    VisualReplaceModeColor = { fg = colors.dark1, bg = colors.bright_red, bold = true },
    VisualReplaceModeSep = { fg = colors.bright_red, bg = colors.light_pink },
    CommandModeColor = { fg = colors.dark1, bg = colors.magenta, bold = true },
    CommandModeSep = { fg = colors.magenta, bg = colors.light_pink },
    VimExModeColor = { link = "CommandModeColor" },
    VimExModeSep = { link = "CommandModeSep" },
    ExModeColor = { link = "CommandModeColor" },
    ExModeSep = { link = "CommandModeSep" },
    PromptModeColor = { link = "CommandModeColor" },
    PromptModeSep = { link = "CommandModeSep" },
    ShellModeColor = { link = "CommandModeColor" },
    ShellModeSep = { link = "CommandModeSep" },
    TerminalModeColor = { link = "CommandModeColor" },
    TerminalModeSep = { link = "CommandModeSep" },
}

for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
end

