color custom

set number
set relativenumber
syntax enable
set background=dark
set autoindent
set smartindent
set expandtab
set nowrap

inoremap {<cr> {<cr>}<c-o>O
inoremap [<cr> [<cr>]<c-o>O
inoremap (<cr> (<cr>)<c-o>O

let g:netrw_winsize = 15
nmap <c-l> :Lexplore<CR>

let s:toggled_term = -1
tmap <Esc> <c-w><s-n>
nmap <c-n> :call ToggleTerminal()<CR>
tmap <c-n> <c-w><s-n> :call ToggleTerminal()<CR>

function! ToggleTerminal()
	if s:toggled_term == -1
		botright terminal ++rows=10
		let s:toggled_term = bufnr("$")
	else
		execute "bd!".s:toggled_term
		let s:toggled_term = -1
	endif
endfunction

autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/
autocmd BufWritePost *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" | redraw!
