#!/bin/bash

showScrot() {
	scrDir="$HOME/Fotos/scr"
	feh "$scrDir/$(ls -t "$scrDir" | head -1)"
}

_git_parse() {
	gitBranch=$(git branch 2>/dev/null | grep '*' | colrm 1 2)

	if test -n "$gitBranch"; then
		if test $(git status -s | grep "M " | wc -l) -gt 0; then
			echo " $gitBranch+ "
		else
			echo " $gitBranch "
		fi
	fi
}

gclv() {
	git clone git@github.com:varnook/$1
}

gcl() {
	git clone https://github.com/$1/$2
}
