#!/bin/bash
cd $HOME/.bashscripts/

if test $(cat sbState) == 0; then
	text=$(date +%H:%M\ \ \ \ \ %a\ %d\ %b)
else
	rxCurr=$(awk '/enp3s0/ {print $2 }' /proc/net/dev)
	txCurr=$(awk '/enp3s0/ {print $10}' /proc/net/dev)
	text=`python "netuse.py" "$rxCurr" "--kB/s" "$txCurr" "ZZ$txPrev"`
	rxPrev=$rxCurr
	txPrev=$txCurr
fi

xsetroot -name " $text"
