#!/bin/bash
cd $HOME/.bashscripts/

rxPrev="10"
txPrev="10"

		rxCurr=$(awk '/enp3s0/ {print $2 }' /proc/net/dev)
		txCurr=$(awk '/enp3s0/ {print $10}' /proc/net/dev)
		echo $txCurr
		text=`python "netuse.py" "$txPrev" "$txCurr" "10" "10"`
		rxPrev=$rxCurr
		txPrev=$txCurr

echo $text
